version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-mortgage
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mortgage
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  db-data:

networks:
  mortgage-network: