name: Mortgage App CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Build & Test with Docker Services
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Start services with docker-compose
        run: docker compose up -d --build

      - name: Wait for PostgreSQL to be ready
        run: |
          until docker exec postgres-mortgage pg_isready -U postgres; do
            echo "Waiting for postgres..."
            sleep 2
          done

      - name: Maven Build (skip checkstyle, ignore test failures)
        run: mvn clean package -Dcheckstyle.skip=true -Dmaven.test.failure.ignore=true

      - name: Run Maven Tests with Coverage (Ignore if none)
        run: mvn test jacoco:report || echo "No tests found or test step failed, continuing..."

      - name: Upload Coverage Report (if exists)
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: target/site/jacoco/index.html
        continue-on-error: true

      - name: Upload Test Results (if exists)
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: target/surefire-reports
        continue-on-error: true

  docker-build:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag the Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mortgage-app:${{ github.sha }} \
                       -t ${{ secrets.DOCKER_USERNAME }}/mortgage-app:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mortgage-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/mortgage-app:latest

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trivy Security Scan
        uses: aquasecurity/trivy-action@v0.11.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/mortgage-app:${{ github.sha }}
          format: table

      - name: Grype Security Scan
        uses: anchore/grype-action@v0.2.0
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/mortgage-app:${{ github.sha }}
