name: CI/CD Pipeline

on: [push, pull_request]

jobs:

  lint-and-format:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Compile before Checkstyle (for dependency resolution)
        run: mvn compile

      - name: Run Checkstyle for Java
        run: mvn checkstyle:check

  build-and-test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Maven Build
        run: mvn clean package

      - name: Run Maven Tests with Coverage
        run: mvn test jacoco:report

      - name: Upload Test Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: target/site/jacoco/index.html

      - name: Upload Test Results (optional)
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports

  docker-build:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: [build-and-test]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Tag the Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/mortgage-app:${{ github.sha }} \
                       -t ${{ secrets.DOCKER_USERNAME }}/mortgage-app:latest .

      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/mortgage-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/mortgage-app:latest

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Trivy Security Scan
        uses: aquasecurity/trivy-action@v0.11.0
        with:
          image-ref: ${{ secrets.DOCKER_USERNAME }}/mortgage-app:${{ github.sha }}
          format: table

      - name: Grype Security Scan
        uses: anchore/grype-action@v0.2.0
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/mortgage-app:${{ github.sha }}
`
